interfaces:
  spine1:
    lo:
      ipv6: "fd::1/128"
    swp1:
      mtu: "9216"
    swp2:
      mtu: "9216"
    swp27:
      mtu: "9216"
    swp28:
      mtu: "9216"
    swp29:
      mtu: "9216"
      ipv4: "10.6.125.66/30"
    swp30:
      mtu: "9216"
      ipv4: "10.6.125.74/30"
    swp31:
      mtu: "9216"
    swp32:
      mtu: "9216"
    bond100:
      slaves: ["swp1","swp2","swp27","swp28"]
      clagid: "100"
      mtu: "9216"
    peerlink:
      slaves: ["swp31","swp32"]
      ip: "169.254.255.1/24"
      peerip: "169.254.255.2"
      backupip: "10.6.127.152"
      mac: "44:38:39:ff:00:03"
      mtu: "9216"

  spine2:
    lo:
      ipv6: "fd::2/128"
    swp1:
      mtu: "9216"
    swp2:
      mtu: "9216"
    swp27:
      mtu: "9216"
    swp28:
      mtu: "9216"
    swp29:
      mtu: "9216"
      ipv4: "10.6.125.70/30"
    swp30:
      mtu: "9216"
      ipv4: "10.6.125.78/30"
    swp31:
      mtu: "9216"
    swp32:
      mtu: "9216"
    bond100:
      slaves: ["swp1","swp2","swp27","swp28"]
      clagid: "100"
      mtu: "9216"
    peerlink:
      slaves: ["swp31","swp32"]
      ip: "169.254.255.2/24"
      peerip: "169.254.255.1"
      backupip: "10.6.127.151"
      mac: "44:38:39:ff:00:03"
      mtu: "9216"

bgp:
  spine1:
    myasn: "64710"
    router_id: "10.6.120.65"
    ipv4_networks: ["10.6.120.0/24"]
    neighbors:
      9k1:
        name: "9k1"
        remote_ip: "10.6.120.65"
        remote_as: "64700"
        password: "password"
      9k2:
        name: "9k2"
        remote_ip: "10.6.120.73"
        remote_as: "64700"
        password: "password"
      spine2:
        name: "spine2"
        remote_ip: "169.254.255.2"
        remote_as: "64710" 

  spine2:
    myasn: "64710"
    router_id: "10.6.120.69"
    ipv4_networks: ["10.6.120.0/24"]
    neighbors:
      9k1:
        name: "9k1"
        remote_ip: "10.6.120.69"
        remote_as: "64700"
        password: "password"
      9k2:
        name: "9k2"
        remote_ip: "10.6.120.77"
        remote_as: "64700"
        password: "password"
      spine1:
        name: "spine1"
        remote_ip: "169.254.255.1"
        remote_as: "64710"

bridges:
  spine1:
    bridge:
      name: "bridge"
      members: ["bond100","peerlink"]
      vlanaware: "yes"
      vids: ["1-100"]

  spine2:
    bridge:
      name: "bridge"
      members: ["bond100","peerlink"]
      vlanaware: "yes"
      vids: ["1-100"]

SVIs:
  spine1:
    v10:
      name: "bridge.10"
      ip: "10.6.120.2/24"
      mac: "00:00:5e:00:01:01"
      virtual: "10.6.120.1/24"

  spine2:
    v10:
      name: "bridge.10"
      ip: "10.6.120.3/24"
      mac: "00:00:5e:00:01:01"
      virtual: "10.6.120.1/24"
