- name: Configure /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: reload networking
  tags:
    - interfaces

- name: Force an interfaces file reload if the ports.conf has changed
  meta: flush_handlers

- name: Configure DHCP relay file
  copy: src=isc-dhcp-relay dest=/etc/default/isc-dhcp-relay
  notify: restart isc-dhcp-relay
  tags:
    - isc-dhcp-relay

- name: Configure PTM
  copy: src=topology.dot dest=/etc/ptm.d/topology.dot
  notify: restart ptmd
