- name: Configure /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: reload networking
  tags:
    - interfaces

- name: Configure /etc/cumulus/ports
  template: src=ports.conf.j2 dest=/etc/cumulus/ports.conf
  notify: restart switchd
  tags:
    - interfaces

- name: Force an interfaces file reload if the ports.conf has changed
  meta: flush_handlers

- name: Configure quagga daemons file
  copy: src=daemons dest=/etc/quagga/daemons backup=yes
  notify: restart quagga
  tags:
    - quagga

- name: Configure zebra daemon file
  template: src=zebra_config.j2 dest=/etc/quagga/zebra.conf
  notify: restart quagga
  tags:
    - quagga

- name: Enable Quagga reload
  copy: src=quagga.default dest=/etc/default/quagga
  notify: restart quagga
  tags:
    - quagga

- name: Force Quagga restart if enabling reload for the first time
  meta: flush_handlers

- name: Configure quagga configuration
  template: src=quagga_config.j2 dest=/etc/quagga/Quagga.conf
#  notify: reload quagga
  notify: restart quagga
  tags:
    - quagga

- name: Configure PTM
  copy: src=topology.dot dest=/etc/ptm.d/topology.dot
  notify: restart ptmd

- name: Verify Quagga is running
  service: name=quagga state=started
  tags:
    - quagga

#- name: Install mgmtvrf
#  apt: name=cl-mgmtvrf state=present
#  tags:
#    - mgmtvrf

#- name: Check if mgmtvrf is installed
#  stat: path=/var/lib/cl-mgmtvrf/mgmtvrf.conf
#  register: mgmtvrf
#  tags:
#    - mgmtvrf

#- name: Setup Mgmtvrf
#  command: cl-mgmtvrf -e
#  when: mgmtvrf.stat.exists == False
#  tags:
#    - mgmtvrf
