interfaces:

  s4k1:
    lo:
      ipv6: "fd::1:1/128"
      ipv4: "10.254.1.1/32"
      clag_anycast: "10.254.4.1"
    eth0:
      ipv4: "10.11.26.37/24"
      gw: "10.11.26.254"
    bond0:
      slaves: ["swp10"]
      clagid: "1"
      mtu: "9000"
    bond1:
      slaves: ["swp30"]
      clagid: "2"
      mtu: "9000"
    bond2:
      slaves: ["swp20"]
      clagid: "3"
      mtu: "9000"

    peerlink:
      slaves: ["swp51","swp52"]
      ip: "169.254.255.1/24"
      peerip: "169.254.255.2"
      backupip: "10.11.26.38"
      mac: "44:38:39:ff:00:01"
      vlans: ["100","200"]
      mtu: "9000"
    swp10:
      mtu: "9216"
    swp30:
      mtu: "9216"
    swp20:
      mtu: "9216"
    swp51:
      mtu: "9216"
    swp52:
      mtu: "9216"
    vni20:
      vni: "20"
      tun_ip: "10.254.1.1"
      mtu: "9000"
    vni30:
      vni: "30"
      tun_ip: "10.254.1.1"
      mtu: "9000"
    vni40:
      vni: "40"
      tun_ip: "10.254.1.1"
      mtu: "9000"
    vni100:
      vni: "100"
      tun_ip: "10.254.1.1"
      mtu: "9000"

  s4k2:
    lo:
      ipv6: "fd::1:2/128"
      ipv4: "10.254.1.2/32"
      clag_anycast: "10.254.4.1"
    eth0:
      ipv4: "10.11.26.38/24"
      gw: "10.11.26.254"
    bond0:
      slaves: ["swp10"]
      clagid: "1"
      mtu: "9000"
    bond1:
      slaves: ["swp30"]
      clagid: "2"
      mtu: "9000"
    bond2:
      slaves: ["swp20"]
      clagid: "3"
      mtu: "9000"
    peerlink:
      slaves: ["swp51","swp52"]
      ip: "169.254.255.2/24"
      peerip: "169.254.255.1"
      backupip: "10.11.26.37"
      mac: "44:38:39:ff:00:01"
      vlans: ["100","200"]
      mtu: "9000"
    swp10:
      mtu: "9216"
    swp30:
      mtu: "9216"
    swp20:
      mtu: "9216"
    swp51:
      mtu: "9216"
    swp52:
      mtu: "9216"
    vni100:
      vni: "100"
      tun_ip: "10.254.1.2"
      mtu: "9000"
    vni20:
      vni: "20"
      tun_ip: "10.254.1.2"
      mtu: "9000"
    vni30:
      vni: "30"
      tun_ip: "10.254.1.2"
      mtu: "9000"
    vni40:
      vni: "40"
      tun_ip: "10.254.1.2"
      mtu: "9000"

  s4k3:
    lo:
      ipv6: "fd::1:3/128"
      ipv4: "10.254.1.3/32"
      clag_anycast: "10.254.4.2"
    eth0:
      ipv4: "10.11.26.39/24"
      gw: "10.11.26.254"
    bond0:
      slaves: ["swp10"]
      clagid: "1"
      mtu: "9000"
    bond1:
      slaves: ["swp30"]
      clagid: "2"
      mtu: "9000"
    bond2:
      slaves: ["swp20"]
      clagid: "3"
      mtu: "9000"
    peerlink:
      slaves: ["swp51","swp52"]
      ip: "169.254.255.1/24"
      peerip: "169.254.255.2"
      backupip: "10.11.26.40"
      mac: "44:38:39:ff:00:02"
      vlans: ["100","200"]
      mtu: "9000"
    swp10:
      mtu: "9216"
    swp30:
      mtu: "9216"
    swp20:
      mtu: "9216"
    swp51:
      mtu: "9216"
    swp52:
      mtu: "9216"
    vni20:
      vni: "20"
      tun_ip: "10.254.1.3"
      mtu: "9000"
    vni30:
      vni: "30"
      tun_ip: "10.254.1.3"
      mtu: "9000"
    vni40:
      vni: "40"
      tun_ip: "10.254.1.3"
      mtu: "9000"
    vni100:
      vni: "100"
      tun_ip: "10.254.1.3"
      mtu: "9000"

  s4k4:
    lo:
      ipv6: "fd::1:4/128"
      ipv4: "10.254.1.4/32"
      clag_anycast: "10.254.4.2"
    eth0:
      ipv4: "10.11.26.40/24"
      gw: "10.11.26.254"
    bond0:
      slaves: ["swp10"]
      clagid: "1"
      mtu: "9000"
    bond1:
      slaves: ["swp30"]
      clagid: "2"
      mtu: "9000"
    bond2:
      slaves: ["swp20"]
      clagid: "3"
      mtu: "9000"
    peerlink:
      slaves: ["swp51","swp52"]
      ip: "169.254.255.2/24"
      peerip: "169.254.255.1"
      backupip: "10.11.26.39"
      mac: "44:38:39:ff:00:02"
      vlans: ["100","200"]
      mtu: "9000"
    swp10:
      mtu: "9216"
    swp30:
      mtu: "9216"
    swp20:
      mtu: "9216"
    swp51:
      mtu: "9216"
    swp52:
      mtu: "9216"
    vni20:
      vni: "20"
      tun_ip: "10.254.1.1"
      mtu: "9000"
    vni30:
      vni: "30"
      tun_ip: "10.254.1.4"
      mtu: "9000"
    vni40:
      vni: "40"
      tun_ip: "10.254.1.4"
      mtu: "9000"
    vni100:
      vni: "100"
      tun_ip: "10.254.1.4"
      mtu: "9000"

bgp:
  s4k1:
    myasn: "64601"
    networks: ["10.254.1.1/32","10.254.2.0/24","10.254.4.1/32"]
    #Internal Fabric ports to run BGP unnumbered on
    internal_fabric:
      interfaces: ["swp49","swp50"]
      description: "Internal Fabric Network"
  
  s4k2:
    myasn: "64602"
    networks: ["10.254.1.2/32","10.254.2.0/24","10.254.4.1/32"]
    #Internal Fabric ports to run BGP unnumbered on
    internal_fabric:
      interfaces: ["swp49","swp50"]
      description: "Internal Fabric Network"

  s4k3:
    myasn: "64603"
    networks: ["10.254.1.3/32","10.254.3.0/24","10.254.4.2/32"]
    #Internal Fabric ports to run BGP unnumbered on
    internal_fabric:
      interfaces: ["swp49","swp50"]
      description: "Internal Fabric Network"

  s4k4:
    myasn: "64604"
    networks: ["10.254.1.4/32","10.254.3.0/24","10.254.4.2/32"]
    #Internal Fabric ports to run BGP unnumbered on
    internal_fabric:
      interfaces: ["swp49","swp50"]
      description: "Internal Fabric Network"

bridges:
  s4k1:
    ixia_vtep:
      name: "ixia_vtep"
      members: ["bond0","bond2","peerlink","vni100"]
    vlan20:
      name: "vlan20"
      members: ["bond1.20","peerlink.20","vni20"]
    vlan30:
      name: "vlan30"
      members: ["bond1.30","peerlink.30","vni30"]
    vlan40:
      name: "vlan40"
      members: ["bond1.40","peerlink.40","vni40"]
    vlan200:
      name: "vlan200"
      members: ["peerlink.200"]
      svi:
        ip: "10.254.2.2/24"
        virtual: "10.254.2.1"
        mac: "00:00:5e:00:01:01"
  s4k2:
    ixia_vtep:
      name: "ixia_vtep"
      members: ["bond0","bond2","peerlink","vni100"]
    vlan20:
      name: "vlan20"
      members: ["bond1.20","peerlink.20","vni20"]
    vlan30:
      name: "vlan30"
      members: ["bond1.30","peerlink.30","vni30"]
    vlan40:
      name: "vlan40"
      members: ["bond1.40","peerlink.40","vni40"]
    vlan200:
      name: "vlan200"
      members: ["peerlink.200"]
      svi:
        ip: "10.254.2.3/24"
        virtual: "10.254.2.1"
        mac: "00:00:5e:00:01:01"

  s4k3:
    ixia_vtep:
      name: "ixia_vtep"
      members: ["bond0","bond2","peerlink","vni100"]
    vlan20:
      name: "vlan20"
      members: ["bond1.20","peerlink.20","vni20"]
    vlan30:
      name: "vlan30"
      members: ["bond1.30","peerlink.30","vni30"]
    vlan40:
      name: "vlan40"
      members: ["bond1.40","peerlink.40","vni40"]
    vlan200:
      name: "vlan200"
      members: ["peerlink.200"]
      svi:
        ip: "10.254.3.2/24"
        virtual: "10.254.3.1"
        mac: "00:00:5e:00:01:01"
  s4k4:
    ixia_vtep:
      name: "ixia_vtep"
      members: ["bond0","bond2","peerlink","vni100"]
    vlan20:
      name: "vlan20"
      members: ["bond1.20","peerlink.20","vni20"]
    vlan30:
      name: "vlan30"
      members: ["bond1.30","peerlink.30","vni30"]
    vlan40:
      name: "vlan40"
      members: ["bond1.40","peerlink.40","vni40"]
    vlan200:
      name: "vlan200"
      members: ["peerlink.200"]
      svi:
        ip: "10.254.3.3/24"
        virtual: "10.254.3.1"
        mac: "00:00:5e:00:01:01"

lnv:
  s4k1:
    src_ip: "10.254.1.1"
    svc_ip: "10.254.0.99"
  s4k2:
    src_ip: "10.254.1.2"
    svc_ip: "10.254.0.99"
  s4k3:
    src_ip: "10.254.1.3"
    svc_ip: "10.254.0.99"
  s4k4:
    src_ip: "10.254.1.4"
    svc_ip: "10.254.0.99"
